cmake_minimum_required(VERSION 4.2)
project(leetcode_dsa_cpp)

set(CMAKE_CXX_STANDARD 14)

include_directories(1331)
include_directories(237)
include_directories(3120)
include_directories(3300)
include_directories(3754)
include_directories(3756_2553)

add_executable(leetcode_dsa_cpp
        1331/leet_1331.cpp
        1331/leet_1331.h
        1331/leet_1331_main.cpp
        1331/leet_1331_main.h
        2144/leet_2144.cpp
        2144/leet_2_2144.cpp
        237/leetcode_237.h
        2540/easy2540.cpp
        2540/easy2540_2.cpp
        27/leet27.cpp
        27/leet27_2.cpp
        28/leet_28.cpp
        3/leet_3.cpp
        3120/leet_3120_first.cpp
        3120/leet_3120_first.h
        3120/leet_3120_second.cpp
        3120/leet_3120_second.h
        3300/leet_3300.cpp
        3300/leet_3300.h
        3754/leet_3754.cpp
        3754/leet_3754.h
        3756_2553/leer_3756_1st.cpp
        3756_2553/leer_3756_1st.h
        3756_2553/leet_2553.cpp
        3756_2553/leet_2553.h
        8/leet_8_first.cpp
        8/leet_8_second.cpp
        876/leet_876.cpp
        26/leet_26.h
        practice/bin.cpp
        3658/leet_3658.h
        3658/leet_3658_second.h
        practice/bin_real_2.cpp
        35/leet_35_second.h
        4/leet_4_3ms.h
        66/leet_66.h
        66/leet_66_second.h
        practice/second_larges.cpp
        70/leet_70.h
        628/leet_628_fail.h
        628/leet_628_second.h
        1464/leet_1464_first.h
        643/leet_643_first.h
        20/leet_20.h
        121/leet_121.cpp
        69/leet_69.h
        1441/leet_1441.h
        877/leet_877_first_fail.h
        3536/leet_first_3536.h
        19/leet_19.h
        3731/leet_3731_first.h
        3731/leet_3731_second.h
        3014/leet_3014_tp.h
        3014/leet_3014_second.h
        3345/leet_3345_first.h
        3945/leet_3945.h
        3945/leet_3945_second.h
        3945/leet_3945_third.h
        169/leet_169_second.h
        169/leet_169_first.h
        2/leet_2_yt_tutorial.h
        2/leet_2.h
        11/leet_11.h
        2996/leet_soln.h
        2996/leet_2996_first.h
        12/leet_12.h
        41/leet_41_first.h
        3090/leet_fail.h
        3090/leet_3090.h
        4010/leet_first.h
        125/leet_first.h
        125/leet_second.h
        3471/leet_3471_first.h
        3512/leet_3512_first.h
        3512/leet_3512_second.h
        3069/leet_3069.h
        3069/leet_3069_second.h
        217/leet_first_217.h
        3622/leet_3622_first.h
        3622/leet_3622_second.h
        136/leet_136_first.h
        136/leet_136_second.h
        3783/leet_3783_first.h
        3718/leet_3718_first.h
        100/leet_100_first.h
        141/leet_141_first.h
        141/leet_141_second.h
        104/leet_104_first.h
        226/leet_226_first.h
        226/leet_226_second.h
        101/leet_101_first.h
        110/leet_110_first.h
        112/leet_112_first.h
        144/leet_144_first.h
        144/leet_144_second.h
        2058/leet_2058_first.h
        559/leet_559_first.h
        3875/leet_3875_first.h
        3876/leet_first_3876.h
        543/leet_543_first.h
        543/leet_543_second.h)
